# Generated by Django 3.2.5 on 2021-08-12 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100, verbose_name='Rue')),
                ('apartment_address', models.CharField(max_length=100, verbose_name='Appartement')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Pays')),
                ('zip_code', models.CharField(max_length=100, verbose_name='Code postal')),
                ('address_type', models.CharField(choices=[('B', 'Livraison'), ('S', 'Facturation')], max_length=1, verbose_name="Type d'adresse")),
                ('default', models.BooleanField(default=False, verbose_name='Adresse par défaut')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Adresse',
                'verbose_name_plural': 'Adresses',
            },
        ),
    ]
