# Generated by Django 3.2.5 on 2021-08-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20210813_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='unread',
            field=models.BooleanField(default=True),
        ),
    ]
