# Generated by Django 3.2.5 on 2021-08-17 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='delete',
            new_name='deleted',
        ),
    ]
