# Generated by Django 3.2.5 on 2021-08-15 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expenses',
            options={'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
    ]
