# Generated by Django 3.2.5 on 2021-08-15 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210815_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='amount',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='reason',
            field=models.TextField(editable=False),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sale_type',
            field=models.CharField(editable=False, max_length=200),
        ),
    ]
