# Generated by Django 3.2.5 on 2021-08-15 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20210815_1731'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'get_latest_by': 'date', 'ordering': ('-date',), 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
    ]
