# Generated by Django 3.2.5 on 2021-08-15 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_sales_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sales',
            options={'get_latest_by': 'date', 'ordering': ('-date', 'amount'), 'verbose_name': 'Sale', 'verbose_name_plural': 'Sales'},
        ),
    ]
