# Generated by Django 3.2.5 on 2021-08-17 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_user'),
        ('reports', '0005_alter_sales_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='payment_charge_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='charge_id', to='payments.payment'),
        ),
        migrations.AddField(
            model_name='sales',
            name='payment_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='payments.payment'),
        ),
    ]
