# Generated by Django 3.2.5 on 2021-08-13 20:51

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={},
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, help_text='Must be greater than price', null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, help_text='Main picture', keep_meta=True, quality=100, size=[500, 500], upload_to='images/foods/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture_2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Second picture', keep_meta=True, null=True, quality=100, size=[500, 500], upload_to='images/foods/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='picture_3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Third picture', keep_meta=True, null=True, quality=100, size=[500, 500], upload_to='images/foods/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='slug',
            field=models.SlugField(help_text='Autofill field', max_length=400),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
