# Generated by Django 3.2.5 on 2021-08-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210813_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
