# Generated by Django 3.2.5 on 2021-08-14 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('steak', 'Steak'), ('vegan', 'Vegan'), ('vegetarian', 'Vegetarian'), ('rice', 'Rice'), ('bread', 'Bread'), ('asian', 'Asian'), ('american', 'American'), ('european', 'European'), ('australian', 'Australian'), ('african', 'African'), ('chenese', 'Chenese'), ('vietnamian', 'Vietnamian'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
